// Generated by view binder compiler. Do not edit!
package com.example.tourassistant.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.tourassistant.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHomeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnBestActivity;

  @NonNull
  public final Button btnMap;

  @NonNull
  public final Button btnRate;

  @NonNull
  public final ImageView imageView2;

  private FragmentHomeBinding(@NonNull ConstraintLayout rootView, @NonNull Button btnBestActivity,
      @NonNull Button btnMap, @NonNull Button btnRate, @NonNull ImageView imageView2) {
    this.rootView = rootView;
    this.btnBestActivity = btnBestActivity;
    this.btnMap = btnMap;
    this.btnRate = btnRate;
    this.imageView2 = imageView2;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnBestActivity;
      Button btnBestActivity = ViewBindings.findChildViewById(rootView, id);
      if (btnBestActivity == null) {
        break missingId;
      }

      id = R.id.btnMap;
      Button btnMap = ViewBindings.findChildViewById(rootView, id);
      if (btnMap == null) {
        break missingId;
      }

      id = R.id.btnRate;
      Button btnRate = ViewBindings.findChildViewById(rootView, id);
      if (btnRate == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      return new FragmentHomeBinding((ConstraintLayout) rootView, btnBestActivity, btnMap, btnRate,
          imageView2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
